# Generated by Django 3.2.3 on 2021-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=10)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['p_name'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('degree', models.CharField(choices=[('Bachelor', 'bachelor'), ('Master', 'master'), ('Exchange Student', 'exchange')], max_length=30)),
                ('start_year', models.IntegerField(default=2015)),
                ('start_month', models.CharField(default='09', max_length=10)),
                ('graduate_year', models.IntegerField(blank=True, null=True)),
                ('graduate_month', models.CharField(blank=True, max_length=10, null=True)),
                ('department', models.CharField(max_length=50)),
                ('seq_id', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['-seq_id'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('start_year', models.IntegerField(default=2018)),
                ('start_month', models.CharField(max_length=10)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
