# Generated by Django 3.2.3 on 2021-06-15 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_honor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award', models.CharField(max_length=50)),
                ('case_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('accept_day', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ['-accept_day'],
            },
        ),
    ]
