# Generated by Django 3.2.3 on 2021-06-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='member',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
