# Generated by Django 3.2.3 on 2021-06-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_competition_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='company_name',
            field=models.CharField(max_length=80),
        ),
    ]
