# Generated by Django 3.2.3 on 2021-06-12 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210612_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='content',
            new_name='text',
        ),
    ]
