# Generated by Django 3.2.3 on 2021-06-12 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_rename_content_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('degree', models.CharField(choices=[('Bachelor', 'bachelor'), ('Master', 'master')], max_length=30, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='p_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
