# Generated by Django 3.2.3 on 2021-06-12 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20210612_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
