# Generated by Django 3.2.3 on 2021-06-12 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_alter_education_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='datetime',
            new_name='graduate_time',
        ),
    ]
