# Generated by Django 3.2.3 on 2021-06-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_rename_datetime_education_graduate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='graduate_time',
        ),
        migrations.AddField(
            model_name='education',
            name='graduate_month',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='education',
            name='graduate_year',
            field=models.IntegerField(default=2019),
        ),
    ]
