# Generated by Django 3.2.3 on 2021-06-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20210612_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduate_month',
            field=models.IntegerField(default=6, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduate_year',
            field=models.IntegerField(default=2019, null=True),
        ),
    ]
