# Generated by Django 3.2.3 on 2021-06-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20210612_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('start_year', models.IntegerField(default=2018)),
                ('start_month', models.CharField(max_length=10)),
                ('end_year', models.IntegerField(blank=True, null=True)),
                ('end_month', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='education',
            name='graduate_month',
            field=models.CharField(blank=True, default='06', max_length=10, null=True),
        ),
    ]
