# Generated by Django 3.2.3 on 2021-06-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_auto_20210614_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('Bachelor', 'bachelor'), ('Master', 'master'), ('Exchange Student', 'exchange')], max_length=30, unique=True),
        ),
    ]
