# Generated by Django 3.2.3 on 2021-06-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_alter_education_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduate_month',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='graduate_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
