# Generated by Django 3.2.3 on 2021-06-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_auto_20210614_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='seq_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('Bachelor', 'bachelor'), ('Master', 'master'), ('Exchange Student', 'exchange')], max_length=30),
        ),
    ]
