# Generated by Django 3.2.3 on 2021-06-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0016_auto_20210614_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-seq_id']},
        ),
        migrations.AlterField(
            model_name='education',
            name='seq_id',
            field=models.IntegerField(unique=True),
        ),
    ]
