# Generated by Django 3.2.3 on 2021-06-14 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20210614_1302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewTable',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
