# Generated by Django 3.2.3 on 2021-06-14 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0018_auto_20210614_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['p_name']},
        ),
    ]
