# Generated by Django 3.2.3 on 2021-06-14 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0019_alter_about_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='start_month',
            field=models.CharField(default='09', max_length=10),
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.IntegerField(default=2015),
        ),
    ]
